CREATE PROCEDURE [GISC].[SP_CREATE_FOLDER]
	@USERNAME VARCHAR(100),
	@FOLDERNAME VARCHAR(100),
	@GUID UNIQUEIDENTIFIER,
	@DATETIME SMALLDATETIME OUTPUT
AS
BEGIN
	SET @DATETIME = SYSUTCDATETIME();
	INSERT INTO [GISC].[FOLDERS] ([USERNAME],[ID],[TITLE],[CREATED])VALUES (@USERNAME,@GUID,@FOLDERNAME,@DATETIME);
END
