CREATE TABLE [GISC].[FOLDERS](
	[USERNAME] [VARCHAR](100) NOT NULL,
	[ID] [UNIQUEIDENTIFIER] NOT NULL,
	[TITLE] [VARCHAR](100) NOT NULL,
	[CREATED] [SMALLDATETIME] NOT NULL,
 CONSTRAINT PK_FOLDERS_ID PRIMARY KEY CLUSTERED (ID)
)
